### ISSUE TITLE
https://charts.alexbabel.com/ 404

### ISSUE THREAD

**Issue by richard-scott** [AlexanderBabel/helm-charts#27]
Your charts URL isn't working:

https://charts.alexbabel.com/

**Comment by AlexanderBabel** [comment]
Just add it with
```
helm repo add alexbabel https://charts.alexbabel.com
```

Btw you can find the list of the charts when adding `index.yaml` to the url -> [https://charts.alexbabel.com/index.yaml](https://charts.alexbabel.com/index.yaml)

**Comment by richard-scott** [comment]
ok, thanks.
